### ISSUE TITLE
Error with Symfony 3.3

### ISSUE THREAD

**Issue by osr7** [matejvelikonja/LabbyBundle#15]
After updating to the just released Symfony 3.3 I get the following error with your bundle:
`Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot dump definition because of invalid class name ('velikonja_labby.pre_sync')`

It worked without problems on Symfony 3.2

**Comment by matejvelikonja** [comment]
i've checked it and it really looks like that it has problem with 3.3. After a really quick look, I could not found what seems to be the problem. Symfony should be backwards compatible.

I'm opened to PR, since atm I don't have time to dig in.

**Comment by alsar** [comment]
I had the same problem a few days ago. It now works again with Symfony v3.3.2

**Comment by matejvelikonja** [comment]
thx @alsar for testing it out.
