### ISSUE TITLE
Timeout exceeded

### ISSUE THREAD

**Issue by peric** [matejvelikonja/LabbyBundle#2]
I've had problems with timeout exceeded during the process of import method in MySqlImporter.

My workaround was to set timeout to 600 seconds here (by default, it's set to 60 seconds) -> https://github.com/matejvelikonja/LabbyBundle/blob/master/Database/Mysql/MySqlImporter.php#L65, but I'm not sure whether there is any better solution?

Problem also appeared during rsync, because it exceeded the timeout of 900 seconds.

Some solutions can be maybe found here:
http://symfony.com/blog/new-in-symfony-2-4-limit-a-process-run-with-an-idle-timeout

**Comment by matejvelikonja** [comment]
I will try to make configurable timeout for MySqlImport. The rsync command should already have timeout config. The filesystem syncing uses external library (SyncFS), which has timeout configurable. Check here https://github.com/matejvelikonja/SyncFS/blob/master/lib/SyncFS/Configuration/Configuration.php#L54

**Comment by peric** [comment]
I've realized that afterwards. Thanks :)

**Comment by matejvelikonja** [comment]
I've added an option for setting process timeout in config file. Check commit 6e858142cf021e45b6ea5aba9f13ac566d9e1bf1.
Please note that this value is set for each process run and not command as whole.

**Comment by peric** [comment]
Nice. I'll close this.
