### ISSUE TITLE
Possibility to run custom commands after sync is finished

### ISSUE THREAD

**Issue by peric** [matejvelikonja/LabbyBundle#3]
Possibility to run some commands (like fos:elastica:populate etc.) would be also a nice feature. This can be also configured in config.yml and then executed afterwards.

**Comment by peric** [comment]
I suggested a solution here https://github.com/matejvelikonja/LabbyBundle/pull/5

**Comment by matejvelikonja** [comment]
Fixed in #6, 9eebf15f9000f49b8b52a7d52877bc9664882133, version 0.1.0
